version: "3.8"
name: motile-dev

configs:
  postgres_config:
    file: "config/postgres/postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    ports:
      - 0.0.0.0:2345:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  motile-exec:
    build: packages/motile-exec
    image: "motiledev/motile-exec:dev"
    restart: on-failure
    ports:
      - 4020:4020
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    develop:
      watch:
        - action: sync
          path: packages/motile-exec
          target: /usr/src/app
        - action: rebuild
          path: packages/motile-exec/package.json
    depends_on:
      - postgres

  motile-core:
    build: packages/motile-core
    image: "motiledev/motile-core:dev"
    develop:
      watch:
        - action: rebuild
          path: packages/motile-core/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      MOTILE_EXEC_URL: http://motile-exec:4020
    ports:
      - 3377:3377
    depends_on:
      - postgres
