version: "3.8"
name: motile

configs:
  postgres_config:
    file: "db/postgres.conf"

volumes:
  pg_data:

services:
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - -c
      - config_file=/etc/postgresql.conf
    configs:
      - source: postgres_config
        target: /etc/postgresql.conf
    ports:
      - 2345:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  motile-exec:
    image: "motiledev/motile-exec:latest"
    restart: on-failure
    ports:
      - 4020:4020
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres

  motile-core:
    image: "motiledev/motile-core:latest"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      MOTILE_EXEC_URL: http://motile-exec:4020
    ports:
      - 3377:3377
    depends_on:
      - postgres
